name: savemoney
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.17.4
  image_picker: 0.6.6+1
  flutter_datetime_picker: ^1.3.5
  flutter_circular_chart: ^0.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_local_notifications: ^1.4.3
  sqflite: ^1.3.0+1
  path_provider: ^1.6.8
  path:
  decimal: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assests/images/header.jpg
    - assests/images/balance.png
    - assests/images/income.png
    - assests/images/expenditure.png
    - assests/icon/finance.svg
    - assests/icon/star.svg
    - assests/images/goalIcon.png

    - assests/icon/revenue.png
    - assests/icon/salary.png
    - assests/icon/store.png
    - assests/icon/graph-1.png
    - assests/icon/interest.png
    - assests/icon/bonus.png
    - assests/icon/gift.png
    - assests/icon/wallet.png

    - assests/icon/cup.png
    - assests/icon/store-3.png
    - assests/icon/home.png
    - assests/icon/coin-10.png
    - assests/icon/car.png
    - assests/icon/shoes.png
    - assests/icon/clothing.png
    - assests/icon/bill.png
    - assests/icon/technology.png
    - assests/icon/tree.png
    - assests/icon/repair-fee.png
    - assests/icon/treatment.png
    - assests/icon/pet.png
    - assests/icon/education.png



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Poppins
      fonts:
        - asset: assests/fonts/Poppins/Poppins-Regular.ttf
        - asset: assests/fonts/Poppins/Poppins-Medium.ttf
          weight: 600
        - asset: assests/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
